Добавлена админка моделям контактов и расписания
web-Nearest-car-wash/car_wash_backend pull request #26
Opened 2023-12-13 09:15 UTC by Anya-sl

Добавлена админка моделям контактов и расписания. Исправлена опечатка в env.example.

2023-12-14 10:23 UTC, Anya-sl commented
Дни недели классом делать не стала, т.к. у нас их всегда 7 и других не бывает. Пошарила в других проектах, вынесла список в константу. Добавила пометку Круглосуточно.
Если замечаний нет, давайте сольем, и я услуги поправлю в другой ветке

2023-12-14 19:35 UTC, jullitka commented on schedule/models.py
> +    )
1. Интересно, можно как-нибудь сделать валидацию внутри модели, чтобы если круглосуточно = тру, то поля opening_time и closing_time не должны быть заполнены. Не уверена, что это нужно, но не возникнет ли путаницы при выводе этих данных?
2. И не помню к какому решению мы пришли по поводу перерыва на обед. Если делаем, то, вилимо, его тоже в модель надо включать, но только в каком формате....

2023-12-14 19:38 UTC, jullitka requested changes
Написала коммент по модели.

2023-12-15 09:53 UTC, Anya-sl commented on schedule/models.py
> +    )
обед на общем созвоне не обсуждали, у дизайнеров нет. А в json хоть где-то была такая инфа по мойкам?

2023-12-15 10:00 UTC, PavelPrist requested changes

2023-12-15 10:06 UTC, Anya-sl commented on schedule/models.py
> +    (1, _('Monday')),
там же переводчик воткнут. Но могу и поправить, тогда и переводчик не нужен

2023-12-15 11:28 UTC, PavelPrist commented on schedule/models.py
> +    )
> обед на общем созвоне не обсуждали, у дизайнеров нет. А в json хоть где-то была такая инфа по мойкам? Очищать время для круглосуточно не уверена, что стоит делать. А над валидацией времени надо подумать, чтобы начало не было позднее окончания. Но это позже можно добавить

валидацию времени можно сделать в серилизаторе. 

или в модели как-то так


from django.core.exceptions import ValidationError
from django.db import models

class YourModel(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    def clean(self):
        if self.start_time >= self.end_time:
            raise ValidationError('Время начала должно быть раньше времени конца работы')

2023-12-18 10:05 UTC, merged