Feature services
web-Nearest-car-wash/car_wash_backend pull request #27
Opened 2023-12-13 09:35 UTC by Anya-sl

2023-12-14 19:50 UTC, jullitka approved these changes

2023-12-15 10:07 UTC, PavelPrist requested changes

2023-12-15 10:07 UTC, PavelPrist commented on contacts/admin.py
> +    """Класс контактов."""
добавить в докстринг админка
везде

2023-12-15 10:07 UTC, PavelPrist commented on services/models.py
> +class Servises(models.Model):
добавить Model в имя класса

2023-12-15 10:07 UTC, PavelPrist commented on services/models.py
> +    """Класс, представляющий модель услуг автомойки."""
попробовать сократить докстринг

2023-12-15 10:07 UTC, PavelPrist commented on services/models.py
> +
кажется надо добавить поле, хотя бы description ? 
имя услуги и ее описание?  или лишнее?

2023-12-18 10:56 UTC, PavelPrist approved these changes

2023-12-18 10:56 UTC, merged