Add/add serializers
web-Nearest-car-wash/car_wash_backend pull request #30
Opened 2023-12-14 20:37 UTC by jullitka

Добавила сериализаторы для карточки мойки и для списка. Они пока одинаковые.

2023-12-14 20:45 UTC, jullitka commented on api/carwash/urls.py
> +v1_router = SimpleRouter()
Почему я взяла SimpleRouter? Где-то видела что Паша использовал DefaultRouter... В чем разница?

2023-12-15 10:00 UTC, PavelPrist requested changes

2023-12-15 10:00 UTC, PavelPrist commented on api/carwash/serializers.py
> +from carwash.models import CarWashModel
предлагаю удалить isort он задолбал))) все же нормально. почему не проходит

2023-12-15 10:00 UTC, PavelPrist commented on api/carwash/urls.py
> +app_name = 'api'
это вроде не нужно

2023-12-15 10:00 UTC, PavelPrist commented on api/carwash/views.py
> +
советую тут добавить список запросов, удобно очень и сразу понятно, кто будет потом это читать.
http_method_names = ['get']

2023-12-15 10:00 UTC, PavelPrist commented on api/carwash/views.py
> +    queryset = CarWashModel.objects.all()
добавить везде докстринги

2023-12-16 08:53 UTC, PavelPrist commented on api/carwash/views.py
> +            nearby_carwashes = CarWashModel.objects.filter(
думаю, что лучше , возможно, использовать в методах self.queryset   потому что он уже задан выше.

2023-12-16 13:03 UTC, Anya-sl commented on api/carwash/views.py
> +from .serializers import CarWashSerializer, CarWashCardSerializer
Так правильно ж ругается isort сначала точки, потом остальное..

2023-12-16 13:03 UTC, Anya-sl commented on api/carwash/views.py
> +        выводит все мойки"""
докстринг принято заканчивать точкой

2023-12-16 20:20 UTC, jullitka commented on api/carwash/serializers.py
> +from carwash.models import CarWashModel
удалила

2023-12-16 20:26 UTC, jullitka commented on api/carwash/serializers.py
> +    """Сериализатор для вывода моек на главной странице"""
Я докстринги обычно для себя пишу.. Как работает джанго примерно понятно, несложно принцип уловить будет незнакомому человеку, который в коде разбираться будет. А вот суть, для чего это в проекте нужно не всегда понятно и забывается.
"Сериализатор модели мойки" - не соглашусь, потому что у меня в данном случае уже два таких сериализатора, но они несут разный смысл, такой, который я написала в докстринге) Ну, предлагайте текст)

2023-12-16 21:42 UTC, jullitka commented on api/carwash/views.py
> +    queryset = CarWashModel.objects.all()
добавила.

2023-12-18 10:10 UTC, PavelPrist approved these changes

2023-12-18 10:10 UTC, merged