changes_in_carwashmodel
web-Nearest-car-wash/car_wash_backend pull request #35
Opened 2023-12-16 19:10 UTC by Aleksandr140590

Внесены изменения по [таске](https://github.com/web-Nearest-car-wash/car_wash_backend/issues/31)

2023-12-16 20:01 UTC, jullitka commented on carwash/models.py
> +    name = models.CharField(verbose_name='Название', null=False, blank=False,
А  нам точно метро нужно?....

2023-12-16 20:12 UTC, jullitka approved these changes
куда-то прайс из модели мойки пропал) Там еще нет полей, связанных с другими моделями. Они ведь будут?

2023-12-17 14:10 UTC, Aleksandr140590 commented on carwash/models.py
> +    name = models.CharField(verbose_name='Название', null=False, blank=False,
Делал по заданию которое оставил Паша. Убрать успеем если что

2023-12-18 10:20 UTC, PavelPrist commented on carwash/models.py
> +    name = models.CharField(verbose_name='Название', null=False, blank=False,
метро обсуждали, и есть в дизайне пока что

2023-12-18 10:49 UTC, PavelPrist requested changes
в модели пока еще не все поля, надо бы добавить?

2023-12-18 10:49 UTC, PavelPrist commented on carwash/models.py
>                               on_delete=models.CASCADE)
on_delete=models.CASCADE  получается, что удалим тип и удалятся все автомойки с этим типом?

может быть models.SET_NULL ?  лучше

2023-12-18 14:54 UTC, PavelPrist requested changes

2023-12-18 14:54 UTC, PavelPrist commented on carwash/models.py
>                               on_delete=models.CASCADE)
лучше поменять на set null

2023-12-18 15:37 UTC, merged