Add rating
web-Nearest-car-wash/car_wash_backend pull request #39
Opened 2023-12-19 10:16 UTC by jullitka

Добавлена модель оценки, работает без пользователя. Никак не ограничивается возможность ставить оценки одним человеком. Поле добавлено в сериализатор.

2023-12-19 16:00 UTC, PavelPrist requested changes

2023-12-19 16:00 UTC, PavelPrist commented on services/admin.py
> +admin.site.register(ServicesModel, ServisesAdmin)
и тут ServicesAdmin

2023-12-20 05:57 UTC, jullitka commented on carwash/models.py
> +SCORES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))
надо тогда в модели расписания тоже убрать, я оформление оттуда сперла)

2023-12-20 08:58 UTC, PavelPrist approved these changes

2023-12-20 08:58 UTC, merged