make schema drf spectacular and 3 adresses ''- open UI API, 'api/sche…
web-Nearest-car-wash/car_wash_backend pull request #4
Opened 2023-12-01 14:25 UTC by PavelPrist

make schema drf spectacular and 3 adresses ''- open UI API, 'api/schema/-dow
nload schema.yaml, api/schema/redoc/- open redoc'

2023-12-01 19:15 UTC, beskrovniibv requested changes
жоско как только смог

2023-12-01 19:15 UTC, beskrovniibv commented on car_wash_backend/urls.py
> +from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
тут нужна one blank line

2023-12-01 19:15 UTC, beskrovniibv commented on poetry.lock
> +name = "referencing"
что это?

2023-12-02 06:43 UTC, PavelPrist commented on car_wash_backend/urls.py
> +from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
> тут нужна one blank line

как раз по твоему Юлин флейк не прошло ))) пришлось убирать

2023-12-02 06:43 UTC, PavelPrist commented on poetry.lock
> +name = "referencing"
> что это?

разные буковки и циферки )))

2023-12-02 06:55 UTC, Aleksandr140590 approved these changes

2023-12-02 08:24 UTC, Anya-sl commented on car_wash_backend/settings.py
> +
Зачем две пустых строки?

2023-12-02 08:24 UTC, Anya-sl commented on car_wash_backend/urls.py
> +from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
Да, isort не ставит между приложениями, только от основных импортов и твоего приложения

2023-12-02 08:24 UTC, Anya-sl commented on pyproject.toml
а poetry сам собирает, да? странно, что не по алфавиту
В requirements было удобно ориентироваться

2023-12-02 09:05 UTC, PavelPrist commented on car_wash_backend/settings.py
> +
> Зачем две пустых строки?

на будущее))

2023-12-02 09:11 UTC, beskrovniibv commented on poetry.lock
> +name = "referencing"
Это так и должно быть?

2023-12-02 09:16 UTC, beskrovniibv approved these changes

2023-12-02 09:16 UTC, merged