All commits from dev to main from start till 20.12.2023
web-Nearest-car-wash/car_wash_backend pull request #50
Opened 2023-12-20 18:29 UTC by PavelPrist

2023-12-24 19:34 UTC, kmvpw requested changes
Тесты не проходят. Решите вопрос с тестами, пришлите на ревью.

2023-12-25 18:55 UTC, kmvpw reviewed
Для текущего понятно - слишком длинное описание. Для последующих PR - просьба писать описание, что было сделаны, какие задачи решены, на что обратить внимание.

Не прошли тесты линтера - нужно исправить, вернуть на ревью.
Не вижу ни одного теста для контроля качества вашего кода. 
Как минимум - покройте кодом ручки, которые передает фронтам.

Для чего у вас два сценария CI/CD ?

2023-12-25 18:55 UTC, kmvpw commented on api/carwash/serializers.py
> +                return 'Круглосуточно'
Предлагаю возвращать не текст, а константы. Константы задать в отдельном файле. В дальнейшем будет возможность вести работу с этими константами, не строками текста.

2023-12-25 18:55 UTC, kmvpw commented on car_wash_backend/settings.py
> +LANGUAGE_CODE = 'en-us'
По коду возвращались ответы на русском языке, в настройках язык по умолчанию английский. Это корректно?

2023-12-25 18:55 UTC, kmvpw commented on api/carwash/serializers.py
> +        current_time = timezone.now().time()
В настройках часовой пояс UTC. Это учитывается при работе данного метода?

2023-12-25 18:55 UTC, kmvpw commented on car_wash_backend/settings.py
> +    'DEFAULT_THROTTLE_RATES': {
Почему именно такие ограничения на пользователя?

2023-12-25 18:55 UTC, kmvpw commented on carwash/models.py
> +    loyalty = models.TextField(verbose_name="Лояльность", null=True,
Не понимаю назначение поля.

2023-12-25 18:55 UTC, kmvpw commented on carwash/models.py
> +    metro = models.ManyToManyField(
У станций метро есть координаты. Ближайшие можно найти поиском. Почему решили сделать спец. поля для связи?

2023-12-25 18:55 UTC, kmvpw commented on carwash/models.py
> +    image = models.URLField(verbose_name='Фото автомойки')
Фото или ссылка на фото?

2023-12-26 09:44 UTC, PavelPrist commented on carwash/models.py
> +    loyalty = models.TextField(verbose_name="Лояльность", null=True,
это боле для программы лояльности мойки.

2023-12-26 10:09 UTC, PavelPrist commented on carwash/models.py
> +    metro = models.ManyToManyField(
1. не совсем понятно, что значит найти поиском?
2. данные хотели взять из базы яндекса, там уже есть координаты у метро ближайшего.

2023-12-26 10:26 UTC, PavelPrist commented on car_wash_backend/settings.py
> +    'DEFAULT_THROTTLE_RATES': {
не знаем))
увеличили на один нолик каждого. Цифры взяты рандомно.

2023-12-26 10:46 UTC, PavelPrist commented
> Для текущего понятно - слишком длинное описание. Для последующих PR - просьба писать описание, что было сделаны, какие задачи решены, на что обратить внимание.
> 
> Не прошли тесты линтера - нужно исправить, вернуть на ревью. Не вижу ни одного теста для контроля качества вашего кода. Как минимум - покройте кодом ручки, которые передает фронтам.
> 
> Для чего у вас два сценария CI/CD ?

Два сценария, чтобы не хранить в одном файле разные job. 1 на PR, второй на деплой

2023-12-27 09:07 UTC, merged